name: DELETE Workflows

# 触发器
on:
#  schedule:
#    - cron: '0 19 * * 0' #每周天在国际标准时间19点(北京时间+8，即 03:00)
  workflow_dispatch:
#    inputs:
#      root_sol:
#        description: "TVBox"
#        required: true
#        default: "tv"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
    - uses: actions/checkout@v2
      # 删除旧的工作流
    - name: Delete TVBox JSON
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0 # 只保留最新1条
        keep_minimum_runs: 0 # 只保留最新1条
