name: Projects

# 触发器
on:
  schedule:
    - cron: '0 19 * * *' #每天在国际标准时间19点(北京时间+8，即 03:00)
  workflow_dispatch:
#    inputs:
#      root_sol:
#        description: "Projects"
#        required: true
#        default: "tv"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 检出代码
    - uses: actions/checkout@v4
      # 删除旧的工作流
    - name: Delete workflow
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 0 #
        keep_minimum_runs: 0 # 
    - name: Clone project
      run: |
        git clone --depth=1 https://github.com/mymine/tv.git Projects
        cp -rf Projects/live/* ./live

        
    - name: Update files github
      uses: EndBug/add-and-commit@v9
      with:
        default_author: github_actions
        message: 'update files actions'
        add: ${{ github.workspace }}/live/*

